### PR TITLE
chore: update to stable snakemake

### PR DESCRIPTION
**Pull request by johanneskoester**
## Summary by CodeRabbit

- **Chores**
	- Updated the dependency specification for the `snakemake` package to ensure a stable version (8.20.0) is used, enhancing the reliability of the environment.

### CODE REVIEW

**Comment by cmeesters** [comment]
oh, hm, why is there now an explicit version instead of the URI?

**Review by cmeesters — APPROVED** [review]

**Comment by johanneskoester** [comment]
Fix incoming: https://github.com/snakemake/snakemake/pull/3077

**Comment by johanneskoester** [comment]
The test still failed...

**Comment by johanneskoester** [comment]
Why the merge already?

**Comment by johanneskoester** [comment]
The fix is not yet released.

**Comment by cmeesters** [comment]
> Why the merge already?

The change is merely in the toml, pointing to an existing snakemake release.

**Pull request merged**
